/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './App.{js,jsx,ts,tsx}',
    './src/**/*.{js,jsx,ts,tsx}',
    './app/**/*.{js,jsx,ts,tsx}',
  ],
  presets: [require('nativewind/preset')],
  theme: {
    extend: {
      colors: {
        // Material 3 tokens from Luminous Mathematics design system
        primary: '#006591',
        'on-primary': '#ffffff',
        'primary-container': '#0ea5e9',
        'on-primary-container': '#003751',
        'primary-fixed': '#c9e6ff',
        'primary-fixed-dim': '#89ceff',
        'on-primary-fixed': '#001e2f',
        'on-primary-fixed-variant': '#004c6e',
        secondary: '#4648d4',
        'on-secondary': '#ffffff',
        'secondary-container': '#6063ee',
        'secondary-fixed': '#e1e0ff',
        'secondary-fixed-dim': '#c0c1ff',
        tertiary: '#855300',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#d88a00',
        'tertiary-fixed': '#ffddb8',
        'tertiary-fixed-dim': '#ffb95f',
        error: '#ba1a1a',
        'error-container': '#ffdad6',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
        background: '#f8f9ff',
        'on-background': '#0b1c30',
        surface: '#f8f9ff',
        'surface-dim': '#cbdbf5',
        'surface-bright': '#f8f9ff',
        'on-surface': '#0b1c30',
        'surface-variant': '#d3e4fe',
        'on-surface-variant': '#3e4850',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#eff4ff',
        'surface-container': '#e5eeff',
        'surface-container-high': '#dce9ff',
        'surface-container-highest': '#d3e4fe',
        'surface-tint': '#006591',
        outline: '#6e7881',
        'outline-variant': '#bec8d2',
        'inverse-surface': '#213145',
        'inverse-on-surface': '#eaf1ff',
        'inverse-primary': '#89ceff',
        'on-secondary-container': '#fffbff',
        'on-tertiary-container': '#4a2c00',
        'on-primary-container': '#003751',
        'on-secondary-fixed': '#07006c',
        'on-secondary-fixed-variant': '#2f2ebe',
        'on-tertiary-fixed': '#2a1700',
        'on-tertiary-fixed-variant': '#653e00',
        success: '#2e7d32',
        warning: '#b26a00',
      },
      fontFamily: {
        'display-lg': ['HankenGrotesk_700Bold'],
        'headline-md': ['HankenGrotesk_600SemiBold'],
        'headline-sm': ['HankenGrotesk_600SemiBold'],
        'title-lg': ['HankenGrotesk_600SemiBold'],
        'body-md': ['HankenGrotesk_400Regular'],
        'body-sm': ['HankenGrotesk_400Regular'],
        'label-sm': ['HankenGrotesk_600SemiBold'],
      },
      fontSize: {
        'display-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em' }],
        'headline-md': ['28px', { lineHeight: '36px', letterSpacing: '-0.01em' }],
        'headline-sm': ['24px', { lineHeight: '32px' }],
        'title-lg': ['18px', { lineHeight: '24px' }],
        'body-md': ['16px', { lineHeight: '24px' }],
        'body-sm': ['14px', { lineHeight: '20px' }],
        'label-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.5px' }],
      },
      spacing: {
        base: '8px',
        'stack-sm': '8px',
        'stack-md': '16px',
        'stack-lg': '32px',
        gutter: '16px',
        'screen-padding': '24px',
        'card-padding': '20px',
      },
      borderRadius: {
        '2xl': '1.5rem',
        '3xl': '1.75rem',
        '4xl': '2rem',
      },
      boxShadow: {
        'level-1': '0 4px 12px rgba(0, 101, 145, 0.05)',
        'level-2': '0 6px 16px rgba(0, 101, 145, 0.08)',
        'level-3': '0 12px 32px rgba(0, 0, 0, 0.12)',
      },
    },
  },
  plugins: [],
};
