# Generated by Django 6.0.6 on 2026-10-05 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='schools.school'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to='schools.school'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='school',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='schools.school'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='billing.subscription'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='billing.subscriptionplan'),
        ),
        migrations.AddField(
            model_name='usagerecord',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_records', to='schools.school'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['school', 'status'], name='billing_inv_school__69702f_idx'),
        ),
        migrations.AddIndex(
            model_name='usagerecord',
            index=models.Index(fields=['school', 'metric', 'period'], name='billing_usa_school__436c1a_idx'),
        ),
        migrations.AddConstraint(
            model_name='usagerecord',
            constraint=models.UniqueConstraint(fields=('school', 'metric', 'period'), name='unique_school_metric_period'),
        ),
    ]
