# Generated by Django 6.0.6 on 2026-10-05 12:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'School Owner'), ('admin', 'School Administrator'), ('teacher', 'Teacher'), ('student', 'Student'), ('parent', 'Parent / Guardian')], max_length=20)),
                ('student_id', models.CharField(blank=True, max_length=50)),
                ('admission_number', models.CharField(blank=True, max_length=50)),
                ('class_level', models.CharField(blank=True, max_length=20)),
                ('class_stream', models.CharField(blank=True, max_length=50)),
                ('parent_email', models.EmailField(blank=True, max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('last_active_at', models.DateTimeField(blank=True, null=True)),
                ('preferences', models.JSONField(blank=True, default=dict)),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memberships_invited', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='schools.school')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['school', 'role', 'user__last_name'],
                'indexes': [models.Index(fields=['user', 'school'], name='memberships_user_id_784bae_idx'), models.Index(fields=['school', 'role', 'is_active'], name='memberships_school__bbfe84_idx'), models.Index(fields=['school', 'class_level', 'is_active'], name='memberships_school__6c9a44_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'school'), name='unique_user_school_membership')],
            },
        ),
    ]
