# Generated by Django 6.0.6 on 2026-10-05 13:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_school_required'),
        ('schools', '0003_school_required'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dailystreak',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='dailystreak',
            constraint=models.UniqueConstraint(fields=('student', 'school', 'date'), name='unique_student_school_streak_date'),
        ),
    ]
