// Centralized Stitch Material Symbols → MaterialIcons mapping.
// Stitch uses Material Symbols Outlined; @expo/vector-icons MaterialIcons is
// the closest bundled equivalent. If a symbol has no equivalent, the caller
// renders a Text fallback with the symbol name.
const ICON_MAP = {
  person: 'person',
  person_outline: 'person-outline',
  lock: 'lock',
  lock_outline: 'lock-outline',
  visibility: 'visibility',
  visibility_off: 'visibility-off',
  arrow_back: 'arrow-back',
  arrow_forward: 'arrow-forward',
  home: 'home',
  dashboard: 'dashboard',
  book: 'book',
  menu_book: 'menu-book',
  book_open: 'book',
  school: 'school',
  auto_awesome: 'auto-awesome',
  spark: 'flash-on',
  smart_toy: 'smart-toy',
  bar_chart: 'bar-chart',
  pie_chart: 'pie-chart',
  trending_up: 'trending-up',
  leaderboard: 'leaderboard',
  groups: 'groups',
  person_add: 'person-add',
  add: 'add',
  add_circle: 'add-circle',
  add_box: 'add-box',
  close: 'close',
  check: 'check',
  check_circle: 'check-circle',
  edit: 'edit',
  delete: 'delete',
  search: 'search',
  notifications: 'notifications',
  notifications_active: 'notifications-active',
  history: 'history',
  settings: 'settings',
  timer: 'timer',
  cloud_off: 'cloud-off',
  wifi_off: 'wifi-off',
  mail: 'mail',
  email: 'mail',
  logout: 'logout',
  login: 'login',
  send: 'send',
  mic: 'mic',
  star: 'star',
  emoji_events: 'emoji-events',
  military_tech: 'military-tech',
  help: 'help',
  info: 'info',
  privacy_tip: 'privacy-tip',
  article: 'article',
  share: 'share',
  refresh: 'refresh',
  more_vert: 'more-vert',
  more_horiz: 'more-horiz',
  filter_list: 'filter-list',
  chevron_right: 'chevron-right',
  chevron_left: 'chevron-left',
  calendar_today: 'calendar-today',
  schedule: 'schedule',
  menu: 'menu',
  quiz: 'quiz',
  functions: 'functions',
  fire: 'local-fire-department',
  bolt: 'bolt',
  lightbulb: 'lightbulb',
  cloud_done: 'cloud-done',
  cloud_upload: 'cloud-upload',
  cloud_download: 'cloud-download',
  dark_mode: 'dark-mode',
  language: 'language',
  description: 'description',
  assignment: 'assignment',
  fact_check: 'fact-check',
  grade: 'grade',
  workspace_premium: 'workspace-premium',
  psychology: 'psychology',
  forum: 'forum',
  chat: 'chat',
  toggle_on: 'toggle-on',
  download: 'download',
  verified: 'verified',
  error_outline: 'error-outline',
  warning: 'warning',
  saved_search: 'saved-search',
  sort: 'sort',
  upload_file: 'upload-file',
  code: 'code',
  straighten: 'straighten',
};

export function mapIcon(symbolName) {
  return ICON_MAP[symbolName] || null;
}

export default mapIcon;
