# Generated by Django 6.0.6 on 2026-09-05 21:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('document_type', models.CharField(choices=[('textbook', 'Textbook chapter'), ('past_paper', 'Past paper'), ('notes', 'Personal notes'), ('worksheet', 'Worksheet'), ('other', 'Other')], default='other', max_length=20)),
                ('file', models.FileField(upload_to='documents/%Y/%m/')),
                ('file_size', models.PositiveIntegerField()),
                ('page_count', models.PositiveIntegerField(blank=True, null=True)),
                ('extracted_text', models.TextField(blank=True, default='')),
                ('processing_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('processing_error', models.TextField(blank=True, default='')),
                ('detected_level', models.CharField(blank=True, default='', max_length=20)),
                ('detected_subject', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to='curriculum.document')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_index', models.PositiveIntegerField()),
                ('page_number', models.PositiveIntegerField(blank=True, null=True)),
                ('content', models.TextField()),
                ('embedding', models.JSONField(blank=True, default=list)),
                ('token_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='curriculum.document')),
            ],
            options={
                'ordering': ['document', 'chunk_index'],
            },
        ),
        migrations.CreateModel(
            name='DocumentQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cited_chunks', models.ManyToManyField(blank=True, related_name='citations', to='curriculum.documentchunk')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='curriculum.document')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='curriculum.documentchatsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_questions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScanJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='scans/%Y/%m/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('ocr', 'Reading image'), ('solving', 'Solving problem'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('extracted_text', models.TextField(blank=True, default='')),
                ('detected_uneb_code', models.CharField(blank=True, default='', max_length=20)),
                ('detected_topic', models.CharField(blank=True, default='', max_length=255)),
                ('problem_text', models.TextField(blank=True, default='')),
                ('solution_text', models.TextField(blank=True, default='')),
                ('solution_steps', models.JSONField(blank=True, default=list)),
                ('final_answer', models.TextField(blank=True, default='')),
                ('similar_problem_ids', models.JSONField(blank=True, default=list)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='documentchunk',
            constraint=models.UniqueConstraint(fields=('document', 'chunk_index'), name='unique_document_chunk'),
        ),
    ]
