# Generated by Django 6.0.6 on 2026-09-07 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanjob',
            name='detected_topic',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='scanjob',
            name='detected_uneb_code',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
