# Generated by Django 6.0.6 on 2026-09-10 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0002_alter_scanjob_detected_topic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='used_vision_ocr',
            field=models.BooleanField(default=False, help_text='True if any page required Gemini Vision OCR fallback during processing (embedded/vector math pdfplumber could not extract as text). Lets the client explain why this document took longer to process.'),
        ),
    ]
