# Generated by Django 6.0.6 on 2026-10-05 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0003_document_used_vision_ocr'),
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='schools.school'),
        ),
        migrations.AddField(
            model_name='documentchatsession',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_chat_sessions', to='schools.school'),
        ),
        migrations.AddField(
            model_name='documentchunk',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_chunks', to='schools.school'),
        ),
        migrations.AddField(
            model_name='documentquestion',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_questions', to='schools.school'),
        ),
        migrations.AddField(
            model_name='scanjob',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scan_jobs', to='schools.school'),
        ),
    ]
