import React, { forwardRef } from 'react';
import { Pressable, Text, View } from 'react-native';
import { CameraView } from 'expo-camera';
import MaterialIcon from './MaterialIcon';

const CameraViewfinder = forwardRef(function CameraViewfinder({ hasPermission, requestPermission, onCapture, onClose, onGallery, flashMode, onToggleFlash, onFlip, className = '' }, ref) {
  if (!hasPermission) return <View className="flex-1 items-center justify-center bg-[#081522] px-8" accessibilityLabel="Camera permission required"><MaterialIcon name="photo_camera" size={44} color="white" /><Text className="font-title-lg mt-4 text-center text-white">Camera access helps solve problems from a photo.</Text><Pressable onPress={requestPermission} className="mt-6 rounded-full bg-primary px-5 py-3" accessibilityRole="button" accessibilityLabel="Allow camera access"><Text className="font-label-sm text-white">Allow camera</Text></Pressable></View>;
  return <View className={`flex-1 bg-black ${className}`}><CameraView ref={ref} facing="back" flash={flashMode} className="absolute inset-0" /><View className="flex-1 justify-between p-6"><View className="flex-row items-center justify-between"><Pressable onPress={onClose} accessibilityRole="button" accessibilityLabel="Close camera"><MaterialIcon name="close" size={28} color="white" /></Pressable><View className="flex-row gap-5"><Pressable onPress={onToggleFlash} accessibilityRole="button" accessibilityLabel="Toggle flash"><MaterialIcon name={flashMode === 'on' ? 'flash_on' : 'flash_off'} size={25} color="white" /></Pressable><Pressable onPress={onFlip} accessibilityRole="button" accessibilityLabel="Flip camera"><MaterialIcon name="flip_camera_ios" size={25} color="white" /></Pressable></View></View><View className="flex-1 items-center justify-center"><View className="h-64 w-64 rounded-3xl border-2 border-primary-fixed" /></View><View className="flex-row items-center justify-between"><Pressable onPress={onGallery} accessibilityRole="button" accessibilityLabel="Choose from gallery" className="h-12 w-12 items-center justify-center rounded-xl bg-white/20"><MaterialIcon name="photo_library" size={24} color="white" /></Pressable><Pressable onPress={onCapture} accessibilityRole="button" accessibilityLabel="Capture problem" className="h-[72px] w-[72px] items-center justify-center rounded-full border-4 border-white bg-primary"><MaterialIcon name="photo_camera" size={30} color="white" /></Pressable><View className="h-12 w-12" /></View></View></View>;
});
export default CameraViewfinder;